language: php

php:
  - 5.3

env:
  - CAKE_VERSION=master

before_script:
  - git clone git://github.com/cakephp/cakephp ../cakephp && cd ../cakephp
  - mv ../cake_GenerateSitemap plugins/GenerateSitemap
  - chmod -R 777 ../cakephp/app/tmp
  - sh -c "mysql -e 'CREATE DATABASE cakephp_test;'"
  - echo "<?php
    class DATABASE_CONFIG {
    public \$test = array(
      'datasource' => 'Database/Mysql',
      'database' => 'cakephp_test',
      'host' => '0.0.0.0',
      'login' => 'travis',
      'host' => '',
      'persistent' => false,
    );
    }" > ../cakephp/app/Config/database.php

script:
  - ./lib/Cake/Console/cake test GenerateSitemap AllTests --stderr